### ISSUE TITLE
Navbar not appearing on mobile view

### ISSUE THREAD

**Issue by app-generator** [codedthemes/datta-able-bootstrap-dashboard#2]
Description:  The navbar is not visible in mobile views.

To Reproduce please execute the steps
1 - Start Template
2 - Change the resolution to 1048x445 (responsive) or bigger - Navbar is there:
![image](https://user-images.githubusercontent.com/51070104/105396584-c0525300-5c28-11eb-9d81-adb164981922.png)

3 - Using a lower resolution, the navbar is not visible anymore - **Iphone X screen ratio**:
![image](https://user-images.githubusercontent.com/51070104/105396730-e677f300-5c28-11eb-98a5-c6ef5094b5d9.png)

4 - Using responsive 972 x 1156 ratio - navbar is not displayed:
![image](https://user-images.githubusercontent.com/51070104/105396804-f7c0ff80-5c28-11eb-9445-2edd83a8046e.png)

Expected behavior
Navbar should be accessible on all resolutions as a full expanded menu or `burger menu` on lower resolutions 

Desktop tests:
 - OS: Windows 10 - Browser Chrome Latest 
 - OS: Windows 10 - Browser Firefox Latest

**Comment by jossgillet** [comment]
same issue here ... any help would be much appreciated ! I spent hours and days working on this theme template, then realized it ain't displaying fine on mobile phones ... it's a shame because it's a great template. Thanks chaps for your help :-)

**Comment by Teraskull** [comment]
@jossgillet These steps are for [this Flask template](https://github.com/app-generator/flask-datta-able). But it shouldn't be much different regarding the HTML. Just add it directly instead of doing step 2.

1. Add this to `navigation.html`:
```html
<header class="navbar pcoded-header navbar-expand-lg navbar-light d-lg-none">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
        <a href="/" class="b-brand">
            <div class="nav-item pcoded-menu-caption">
                <!-- Your logo img here -->
            </div>
        </a>
    </div>
</header>
```

2. Then, in `base.html` add:
```html
<!-- Top Bar -->
{% include 'includes/navigation.html' %}
```
So that it is below this line:
```html
<!-- SideBar -->
{% include 'includes/sidebar.html' %}
```

That should be all for the mobile top bar to appear. Let me know if it works for you.

**Comment by asofiasbo** [comment]
@Teraskull I'm working with the Django template, and this **almost** worked 100% for me. 

With that `navigation.html` I was getting the following:


  first               | second            |  third
:-------------------------:|:-------------------------:|:-------------------------:
<img width="606" alt="Screenshot 2021-05-23 at 11 20 44" src="https://user-images.githubusercontent.com/22176365/119256761-27255000-bbba-11eb-857d-8ee62b331bd6.png"> | <img width="604" alt="Screenshot 2021-05-23 at 11 20 50" src="https://user-images.githubusercontent.com/22176365/119256593-51c2d900-bbb9-11eb-91c5-d38cc638f980.png"> | <img width="599" alt="Screenshot 2021-05-23 at 11 21 01" src="https://user-images.githubusercontent.com/22176365/119256594-54253300-bbb9-11eb-874d-f3ef9254f206.png">


I fixed it by also adding this to `styles.css`:
```
@media only screen and (max-width: 991px) {
  .pcoded-header {
    width: 100%;
    margin-left: 0;
  }
}
```
After: 
<img width="602" alt="Screenshot 2021-05-23 at 11 21 13" src="https://user-images.githubusercontent.com/22176365/119256883-b6cafe80-bbba-11eb-97d5-e740fdc7e2ee.png">

**Comment by phoenixcoded20** [comment]
This is resolved in latest version. Thanks for reporting.
